name: Upload Artifact Example

on:
  push:
    branches:
      - main  # Run on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository

      - name: Create an artifact
        run: |
          echo "Hello, world!" > artifact.txt  # Create a simple text file

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # Correctly using v3 now
        with:
          name: my-artifact  # Artifact name
          path: artifact.txt  # Path to the file you want to upload
