name: Upload Artifact Example

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Create an artifact
        run: |
          echo "Hello, world!" > artifact.txt  # Create a simple text file

      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Use the stable v2 version of upload-artifact
        with:
          name: my-artifact  # Name of the artifact
          path: artifact.txt  # Path to the artifact
